[alembic]
script_location = migrations
time_zone = UTC
file_template = %%(rev)s_%%(slug)s
version_path_separator = os
sqlalchemy.url = postgresql+psycopg2://postgres:123@localhost:5432/uae_sale

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
formatter = generic
args = (sys.stderr,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s