"""Add encrypted card payment tracking

Revision ID: 020727b020e8
Revises: d108cf8a37d4
Create Date: 2025-10-23 22:02:06.165475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020727b020e8'
down_revision = 'd108cf8a37d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('package', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('card_last_4', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('card_bin', sa.String(length=6), nullable=True),
    sa.Column('encrypted_data', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_payments_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_card_payments_created_at'))

    op.drop_table('card_payments')
    # ### end Alembic commands ###
