"""add_supplier_id_to_purchases

Revision ID: 409958037ba0
Revises: bb18b40801a9
Create Date: 2025-10-17 16:21:27.845143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409958037ba0'
down_revision = 'bb18b40801a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchases_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key('fk_purchases_supplier_id', 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchases_supplier_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchases_supplier_id'))
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
