"""Add logo_path and watermark_image_path to invoice_settings

Revision ID: 4b866d5e4c3c
Revises: 
Create Date: 2025-10-23 11:19:53.299655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b866d5e4c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('watermark_image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_settings', schema=None) as batch_op:
        batch_op.drop_column('watermark_image_path')
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
