"""Add Payment Vault models for secure payment management

Revision ID: 7216e668bf04
Revises: fabdb437da0f
Create Date: 2025-10-23 16:48:59.910330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216e668bf04'
down_revision = 'fabdb437da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_password_hash', sa.String(length=255), nullable=False),
    sa.Column('vault_name', sa.String(length=100), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('nowpayments_api_key', sa.String(length=255), nullable=True),
    sa.Column('nowpayments_ipn_secret', sa.String(length=255), nullable=True),
    sa.Column('bitcoin_address', sa.String(length=255), nullable=True),
    sa.Column('ethereum_address', sa.String(length=255), nullable=True),
    sa.Column('usdt_address', sa.String(length=255), nullable=True),
    sa.Column('min_donation_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_donation_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('require_2fa', sa.Boolean(), nullable=True),
    sa.Column('auto_lock_minutes', sa.Integer(), nullable=True),
    sa.Column('max_failed_attempts', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['payment_vault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('crypto_currency', sa.String(length=10), nullable=False),
    sa.Column('payment_address', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['payment_vault.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transactions')
    op.drop_table('payment_logs')
    op.drop_table('payment_vault')
    # ### end Alembic commands ###
