"""add_cheques_table

Revision ID: 78197ecf60d0
Revises: 409958037ba0
Create Date: 2025-10-17 17:45:44.256450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78197ecf60d0'
down_revision = '409958037ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheque_number', sa.String(length=50), nullable=False),
    sa.Column('cheque_bank_number', sa.String(length=50), nullable=False),
    sa.Column('cheque_type', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('bank_branch', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('amount_aed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('drawer_name', sa.String(length=200), nullable=True),
    sa.Column('drawer_id_number', sa.String(length=50), nullable=True),
    sa.Column('payee_name', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bounce_reason', sa.String(length=500), nullable=True),
    sa.Column('days_until_due', sa.Integer(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cheques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cheques_cheque_number'), ['cheque_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cheques_cheque_type'), ['cheque_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_is_overdue'), ['is_overdue'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_receipt_id'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cheques_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cheques_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_cheques_status'))
        batch_op.drop_index(batch_op.f('ix_cheques_sale_id'))
        batch_op.drop_index(batch_op.f('ix_cheques_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_cheques_is_overdue'))
        batch_op.drop_index(batch_op.f('ix_cheques_is_active'))
        batch_op.drop_index(batch_op.f('ix_cheques_expense_id'))
        batch_op.drop_index(batch_op.f('ix_cheques_due_date'))
        batch_op.drop_index(batch_op.f('ix_cheques_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cheques_cheque_type'))
        batch_op.drop_index(batch_op.f('ix_cheques_cheque_number'))

    op.drop_table('cheques')
    # ### end Alembic commands ###
