"""Add integration_settings table for WhatsApp Email Redis Currency API

Revision ID: c318c5e4c3db
Revises: update_watermark_settings
Create Date: 2025-10-23 15:37:12.802591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c318c5e4c3db'
down_revision = 'update_watermark_settings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=20), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_settings_service_name'), ['service_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_settings_service_name'))

    op.drop_table('integration_settings')
    # ### end Alembic commands ###
