"""Add purchase fields to donations table

Revision ID: d108cf8a37d4
Revises: 7216e668bf04
Create Date: 2025-10-23 21:33:40.493445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd108cf8a37d4'
down_revision = '7216e668bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('package', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('package')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
