"""Add Donation model for tracking donations and crypto payments

Revision ID: fabdb437da0f
Revises: c318c5e4c3db
Create Date: 2025-10-23 16:01:22.022479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabdb437da0f'
down_revision = 'c318c5e4c3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('crypto_type', sa.String(length=20), nullable=True),
    sa.Column('wallet_address', sa.String(length=200), nullable=True),
    sa.Column('transaction_hash', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('donor_name', sa.String(length=200), nullable=True),
    sa.Column('donor_email', sa.String(length=200), nullable=True),
    sa.Column('donor_message', sa.Text(), nullable=True),
    sa.Column('converted_to_crypto', sa.Boolean(), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('final_wallet_address', sa.String(length=200), nullable=True),
    sa.Column('gateway_name', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_status', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('thank_you_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))

    op.drop_table('donations')
    # ### end Alembic commands ###
